# Generated by Django 5.2.9 on 2026-07-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_seed_hargrove_q1_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hargrovemetricoverride',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
