repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args: ["--config-file=pyproject.toml", "--show-traceback"]
        additional_dependencies:
            # plugin
            - django-stubs
            # django + third-party apps referenced in INSTALLED_APPS
            - django>=5.2.6,<6
            - djangorestframework
            - django-filter
            - django-stubs-ext
            - django-allauth>=65
            - drf-spectacular
            - django-cors-headers
            - python-dotenv
            - dj-database-url
            - whitenoise
            - psycopg[binary]>=3
            - django-browser-reload>=1.18.0
            - types-Markdown
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-django
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-ll","-q"]
  - repo: https://github.com/pypa/pip-audit
    rev: v2.9.0
    hooks:
      - id: pip-audit
        args: ["-r", "requirements.txt"]
