repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--config-file=pyproject.toml"]
        additional_dependencies:
            # plugin
            - django-stubs
            # django + third-party apps referenced in INSTALLED_APPS
            - django>=5,<6
            - djangorestframework
            - django-filter
            - drf-spectacular
            - django-cors-headers
            - django-environ>=0.12.0
            - whitenoise
            - psycopg[binary]>=3
            - django-browser-reload>=1.18.0
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.35.2
    hooks:
      - id: djlint-django
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-ll","-q"]
  - repo: https://github.com/pypa/pip-audit
    rev: v2.7.3
    hooks:
      - id: pip-audit
