# Generated by Django 5.2.7 on 2025-10-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='behavioral_health',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
