# Generated by Django 5.2.9 on 2026-02-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='aud',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='three_c_client',
            field=models.BooleanField(blank=True, db_column='3c_client', null=True),
        ),
    ]
