# Generated by Django 5.2.9 on 2026-04-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patients_aud_patients_latitude_patients_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounters',
            name='diversion_type_cat1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='encounters',
            name='diversion_type_cat2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='encounters',
            name='med_manage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounters',
            name='med_script',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounters',
            name='pcp_connect',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounters',
            name='survey_willing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odreferrals',
            name='diversion_type_cat1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='odreferrals',
            name='diversion_type_cat2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='odreferrals',
            name='encounter_type_cat1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='odreferrals',
            name='encounter_type_cat2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='odreferrals',
            name='encounter_type_cat3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='odreferrals',
            name='med_manage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odreferrals',
            name='med_script',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odreferrals',
            name='od_district',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='odreferrals',
            name='pcp_connect',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odreferrals',
            name='survey_willing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='aud_sus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='bh_sus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='case_management',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='flyer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='is_high_utilizer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='safety_plan',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='sud_sus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referrals',
            name='diversion_type_cat1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='referrals',
            name='diversion_type_cat2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='referrals',
            name='med_manage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referrals',
            name='med_script',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referrals',
            name='pcp_connect',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referrals',
            name='survey_willing',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
