# Generated by Django 5.2.9 on 2026-06-04

import django.db.models.deletion
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_backfill_default_agency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounters",
            name="agency",
            field=models.ForeignKey(
                default=apps.core.models.get_default_agency_id,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.agency",
            ),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="agency",
            field=models.ForeignKey(
                default=apps.core.models.get_default_agency_id,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.agency",
            ),
        ),
        migrations.AlterField(
            model_name="patients",
            name="agency",
            field=models.ForeignKey(
                default=apps.core.models.get_default_agency_id,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.agency",
            ),
        ),
        migrations.AlterField(
            model_name="referrals",
            name="agency",
            field=models.ForeignKey(
                default=apps.core.models.get_default_agency_id,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.agency",
            ),
        ),
    ]
