# Generated by Copilot on 2025-10-13
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.IntegerField(choices=[(1, "Low"), (2, "Medium"), (3, "High")], default=2),
        ),
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                related_name="assigned_tasks",
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("is_completed", "-created_at")},
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["is_completed", "-created_at"], name="tasks_task_is_comp_d2a19a_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["priority"], name="tasks_task_priority_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["due_date"], name="tasks_task_due_date_idx"),
        ),
    ]
