# Generated by Django 5.2.7 on 2025-10-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_priority_due_assignee'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_is_comp_2b457e_idx',
            old_name='tasks_task_is_comp_d2a19a_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_priorit_a900d4_idx',
            old_name='tasks_task_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_due_dat_bce847_idx',
            old_name='tasks_task_due_date_idx',
        ),
    ]
