# Generated by Django 5.1.6 on 2025-03-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounters',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('referral_ID', models.IntegerField()),
                ('port_referral_ID', models.IntegerField()),
                ('patient_ID', models.IntegerField()),
                ('encounter_date', models.DateField()),
                ('pcp_agency', models.CharField(max_length=50)),
                ('encounter_type_cat1', models.CharField(max_length=50)),
                ('encounter_type_cat2', models.CharField(max_length=50)),
                ('encounter_type_cat3', models.CharField(max_length=50)),
                ('encounter_stage', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_3c', models.IntegerField()),
                ('age', models.IntegerField()),
                ('case_management', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('insurance', models.CharField(max_length=50)),
                ('pcp_agency', models.CharField(max_length=50)),
                ('race', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=20)),
                ('sud', models.BooleanField()),
                ('zip_code', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
                ('modified_date', models.DateField()),
                ('marital_status', models.CharField(max_length=30)),
                ('veteran_status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('patient_ID', models.IntegerField()),
                ('created', models.DateField()),
                ('date_received', models.DateField()),
                ('referral_agency', models.CharField(max_length=50)),
                ('encounter_type_cat1', models.CharField(max_length=50)),
                ('encounter_type_cat2', models.CharField(max_length=50)),
                ('encounter_type_cat3', models.CharField(max_length=50)),
                ('referral_type_0', models.CharField(max_length=50)),
                ('referral_type_1', models.CharField(max_length=50)),
                ('referral_type_2', models.CharField(max_length=50)),
                ('referral_type_3', models.CharField(max_length=50)),
                ('referral_type_4', models.CharField(max_length=50)),
            ],
        ),
    ]
