# Generated by Django 5.2 on 2025-04-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="odreferrals",
            name="od_time",
        ),
    ]
