# Generated by Django 5.2 on 2025-04-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_remove_odreferrals_od_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odreferrals",
            name="narcan_prior_to_ems_dosage",
            field=models.FloatField(),
        ),
    ]
