# Generated by Django 5.2 on 2025-04-30 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_odreferrals_narcan_prior_to_ems_dosage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="odreferrals",
            name="no_referral_reason",
        ),
    ]
