# Generated by Django 5.2 on 2025-05-01 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_remove_odreferrals_no_referral_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encounters",
            name="encounter_stage",
        ),
    ]
