# Generated by Django 5.2 on 2025-05-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_remove_encounters_encounter_stage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patients",
            name="case_management",
        ),
        migrations.RemoveField(
            model_name="patients",
            name="client_3c",
        ),
        migrations.RemoveField(
            model_name="patients",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="referrals",
            name="created",
        ),
        migrations.RemoveField(
            model_name="referrals",
            name="referral_type_0",
        ),
        migrations.RemoveField(
            model_name="referrals",
            name="referral_type_1",
        ),
        migrations.RemoveField(
            model_name="referrals",
            name="referral_type_2",
        ),
        migrations.RemoveField(
            model_name="referrals",
            name="referral_type_3",
        ),
        migrations.RemoveField(
            model_name="referrals",
            name="referral_type_4",
        ),
        migrations.AddField(
            model_name="referrals",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="referrals",
            name="insurance",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="referrals",
            name="referral_1",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="referrals",
            name="referral_2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="referrals",
            name="referral_3",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="referrals",
            name="referral_4",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="referrals",
            name="referral_5",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="referrals",
            name="referral_closed_reason",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="referrals",
            name="sex",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="referrals",
            name="zipcode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="encounters",
            name="encounter_date",
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="encounters",
            name="encounter_type_cat1",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="encounters",
            name="encounter_type_cat2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="encounters",
            name="encounter_type_cat3",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="encounters",
            name="patient_ID",
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="encounters",
            name="pcp_agency",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="encounters",
            name="port_referral_ID",
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="encounters",
            name="referral_ID",
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="accepted_other",
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="accepted_pbh",
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="accepted_rediscovery",
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="accepted_reflections",
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="bup_admin",
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="bup_already_prescribed",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="bup_not_indicated_reason",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="client_agrees_to_mat",
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="contact_level_other",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="contact_level_pbh",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="contact_level_rediscovery",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="contact_level_reflections",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="cpm_disposition",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="cpm_notification",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="cpr_administered",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="delay_in_referral",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="disposition",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="engagement_location",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="is_bup_indicated",
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="lat",
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="leave_behind_narcan_amount",
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="living_situation",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="long",
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="narcan_by_ems_dosage",
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="narcan_doses_by_ems",
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="narcan_doses_prior_to_ems",
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="narcan_given",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="narcan_prior_to_ems_dosage",
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="number_of_ems_onscene",
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="number_of_nonems_onscene",
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="number_of_peers_onscene",
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="number_of_police_onscene",
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="od_address",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="overdose_recent",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="patient_age",
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="patient_id",
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="patient_insurance",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="patient_sex",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="patient_zipcode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="persons_trained",
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="police_ita",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="referral_agency",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="referral_other",
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="referral_pbh",
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="referral_rediscovery",
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="referral_reflections",
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="referral_source",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="referral_to_sud_agency",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="suspected_drug",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="transport_to_location",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="transported_by",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="patients",
            name="age",
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="patients",
            name="created_date",
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="patients",
            name="insurance",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="patients",
            name="marital_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="patients",
            name="modified_date",
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="patients",
            name="pcp_agency",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="patients",
            name="race",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="patients",
            name="sex",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="patients",
            name="sud",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patients",
            name="veteran_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="patients",
            name="zip_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="referrals",
            name="date_received",
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="referrals",
            name="encounter_type_cat1",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="referrals",
            name="encounter_type_cat2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="referrals",
            name="encounter_type_cat3",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="referrals",
            name="patient_ID",
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="referrals",
            name="referral_agency",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
