# Generated by Django 5.2.4 on 2025-07-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_odreferrals_jail_end_1_odreferrals_jail_end_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odreferrals",
            name="jail_end_1",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="jail_end_2",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="jail_start_1",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="jail_start_2",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
