# Generated by Django 5.2.4 on 2025-07-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_alter_odreferrals_jail_end_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odreferrals",
            name="od_date",
            field=models.DateField(default=None, null=True),
        ),
    ]
