# Generated by Django 5.2.4 on 2025-07-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_alter_odreferrals_od_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odreferrals",
            name="jail_end_1",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="jail_end_2",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="jail_start_1",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="jail_start_2",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="odreferrals",
            name="od_date",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
