# Generated by Django 5.2.9 on 2026-06-04

import django.db.models.deletion
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_enforce_non_null_agency_fks"),
        ("accounts", "0005_user_agency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="agency",
            field=models.ForeignKey(
                default=apps.accounts.models.get_default_agency_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="core.agency",
            ),
        ),
    ]
