# Generated by Django 5.2.5 on 2025-09-23 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['-featured', 'featured_rank', '-published_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='casestudy',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='featured_rank',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers show first'),
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='tags',
        ),
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['featured', 'featured_rank'], name='blog_casest_feature_79a179_idx'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='case_studies', to='blog.tag'),
        ),
    ]
