# Generated by Django 5.2.9 on 2026-04-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagingencounter',
            name='row_status',
            field=models.CharField(choices=[('new', 'New'), ('existing', 'Existing'), ('changed', 'Changed'), ('warning', 'Warning'), ('error', 'Error')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='stagingodreferral',
            name='row_status',
            field=models.CharField(choices=[('new', 'New'), ('existing', 'Existing'), ('changed', 'Changed'), ('warning', 'Warning'), ('error', 'Error')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='stagingpatient',
            name='row_status',
            field=models.CharField(choices=[('new', 'New'), ('existing', 'Existing'), ('changed', 'Changed'), ('warning', 'Warning'), ('error', 'Error')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='stagingreferral',
            name='row_status',
            field=models.CharField(choices=[('new', 'New'), ('existing', 'Existing'), ('changed', 'Changed'), ('warning', 'Warning'), ('error', 'Error')], default='new', max_length=10),
        ),
    ]
