# Generated by Django 5.2.9 on 2026-04-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0002_alter_stagingencounter_row_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimportfile',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
