# Generated by Django 5.2.9 on 2026-04-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0003_dataimportfile_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagingencounter',
            name='diversion_type_cat1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stagingencounter',
            name='diversion_type_cat2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stagingencounter',
            name='med_manage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingencounter',
            name='med_script',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingencounter',
            name='pcp_connect',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingencounter',
            name='survey_willing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingodreferral',
            name='diversion_type_cat1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stagingodreferral',
            name='diversion_type_cat2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stagingodreferral',
            name='encounter_type_cat1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stagingodreferral',
            name='encounter_type_cat2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stagingodreferral',
            name='encounter_type_cat3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stagingodreferral',
            name='med_manage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingodreferral',
            name='med_script',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingodreferral',
            name='od_district',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stagingodreferral',
            name='pcp_connect',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingodreferral',
            name='survey_willing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingpatient',
            name='aud_sus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingpatient',
            name='bh_sus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingpatient',
            name='case_management',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingpatient',
            name='flyer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingpatient',
            name='is_high_utilizer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingpatient',
            name='safety_plan',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingpatient',
            name='sud_sus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingreferral',
            name='diversion_type_cat1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stagingreferral',
            name='diversion_type_cat2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='stagingreferral',
            name='med_manage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingreferral',
            name='med_script',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingreferral',
            name='pcp_connect',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingreferral',
            name='survey_willing',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
