# Generated by Django 5.2.9 on 2026-04-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0004_stagingencounter_diversion_type_cat1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinglog',
            name='file_type',
            field=models.CharField(blank=True, choices=[('patients', 'Patients'), ('referrals', 'Referrals'), ('odreferrals', 'OD Referrals'), ('encounters', 'Encounters')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='processinglog',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
