# Generated by Django 5.2.9 on 2026-04-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0005_processinglog_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagingpatient',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
