# Generated by Django 5.2.9 on 2026-06-04 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seed_default_tenants'),
        ('data_import', '0006_stagingpatient_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimportbatch',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_import_batches', to='core.agency'),
        ),
        migrations.AddField(
            model_name='dataimportbatch',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_import_batches', to='core.county'),
        ),
        migrations.AddField(
            model_name='stagingencounter',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.agency'),
        ),
        migrations.AddField(
            model_name='stagingodreferral',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.agency'),
        ),
        migrations.AddField(
            model_name='stagingpatient',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.agency'),
        ),
        migrations.AddField(
            model_name='stagingreferral',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.agency'),
        ),
    ]
