name: CI
on:
    pull_request:
    push:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:16
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: cpmdash_test
                ports: ["5432:5432"]
                options: >-
                    --health-cmd="pg_isready -U postgres"
                    --health-interval=10s --health-timeout=5s --health-retries=5
        env:
            DATABASE_URL: postgresql://postgres:postgres@localhost:5432/cpmdash_test
            DJANGO_SETTINGS_MODULE: cpmdash.settings
            SECRET_KEY: test-secret
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with: { python-version: "3.12" }
            - name: Install uv
              run: curl -LsSf https://astral.sh/uv/install.sh | sh && echo "$HOME/.local/bin" >> $GITHUB_PATH
            - name: Sync deps
              run: uv sync --dev
            - name: Lint & format
              run: uv run ruff check && uv run ruff format --check
            - name: Type check
              run: uv run mypy
            - name: Migration check
              run: uv run python src/manage.py makemigrations --check --dry-run
            - name: Tests
              run: uv run pytest

    docker:
        runs-on: ubuntu-latest
        needs: [test]
        if: github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v4
            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: ghcr.io/${{ github.repository }}:latest
